"""Subagent runtime: configuration, coordinator, child tasks (design §Subagent runtime).

Includes the configuration contract, per-run coordinator (FIFO scheduling,
cancellation and timeouts), child runtime, manual pending selection, and child
transcript path helpers.
"""

from .config_loader import (
    MAX_CATALOG_AGENTS,
    MAX_FILE_BYTES,
    AgentConfigLoader,
    AgentRegistry,
    resolve_child_model_config,
)
from .coordinator import (
    EVENT_SUBAGENT_STATUS_CHANGED,
    ChildRunnerProtocol,
    CoordinatorClosedError,
    SubagentCoordinator,
    UnknownTaskError,
    WaitOutcome,
)
from .pending import PendingSubagentSelection
from .persistence import child_transcript_dir
from .types import (
    DEFAULT_TASK_TIMEOUT_SECONDS,
    MAX_COMBINED_CONTEXT_CHARS,
    MAX_DEFAULT_SKILLS,
    MAX_DESCRIPTION_CHARS,
    MAX_INSTRUCTIONS_CHARS,
    MAX_MODEL_BASE_URL_CHARS,
    MAX_MODEL_FIELD_CHARS,
    MAX_NAME_CHARS,
    MAX_PROMPT_CHARS,
    MAX_TASK_TIMEOUT_SECONDS,
    MAX_TOOLS_ALLOW,
    MAX_TOOLS_DENY,
    MIN_TASK_TIMEOUT_SECONDS,
    PERMISSION_PROFILES,
    SUBAGENT_TOOLS,
    TASK_ID_PREFIX,
    TERMINAL_STATUSES,
    VALID_PROFILES,
    AgentConfig,
    AgentConfigSet,
    AgentIssue,
    AgentSource,
    ModelOverride,
    SubagentCancelReason,
    SubagentRequest,
    SubagentResult,
    SubagentStatus,
    SubagentTaskSnapshot,
    ToolsSpec,
    effective_tool_names,
    generate_task_id,
    is_terminal_status,
    is_valid_task_id,
    transition_allowed,
)

__all__ = [
    "DEFAULT_TASK_TIMEOUT_SECONDS",
    "EVENT_SUBAGENT_STATUS_CHANGED",
    "MAX_CATALOG_AGENTS",
    "MAX_COMBINED_CONTEXT_CHARS",
    "MAX_DEFAULT_SKILLS",
    "MAX_DESCRIPTION_CHARS",
    "MAX_FILE_BYTES",
    "MAX_INSTRUCTIONS_CHARS",
    "MAX_MODEL_BASE_URL_CHARS",
    "MAX_MODEL_FIELD_CHARS",
    "MAX_NAME_CHARS",
    "MAX_PROMPT_CHARS",
    "MAX_TASK_TIMEOUT_SECONDS",
    "MAX_TOOLS_ALLOW",
    "MAX_TOOLS_DENY",
    "MIN_TASK_TIMEOUT_SECONDS",
    "PERMISSION_PROFILES",
    "SUBAGENT_TOOLS",
    "TASK_ID_PREFIX",
    "TERMINAL_STATUSES",
    "VALID_PROFILES",
    "AgentConfig",
    "AgentConfigLoader",
    "AgentConfigSet",
    "AgentIssue",
    "AgentRegistry",
    "AgentSource",
    "ChildRunnerProtocol",
    "CoordinatorClosedError",
    "ModelOverride",
    "PendingSubagentSelection",
    "SubagentCancelReason",
    "SubagentCoordinator",
    "SubagentRequest",
    "SubagentResult",
    "SubagentStatus",
    "SubagentTaskSnapshot",
    "ToolsSpec",
    "UnknownTaskError",
    "WaitOutcome",
    "child_transcript_dir",
    "effective_tool_names",
    "generate_task_id",
    "is_terminal_status",
    "is_valid_task_id",
    "resolve_child_model_config",
    "transition_allowed",
]
